export const mockData = [
  {
    name: "George",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "1111",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "2222",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "333",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "4444",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "555",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "666",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "7777",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "8888",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "9999",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "aaaa",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "bbbb",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "cccc",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "dddd",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "eeee",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "fffff",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "gggg",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "hhhh",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "iiii",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "jjjj",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "kkk",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "lll",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "mmm",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "ncmx",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "npnoinpds",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "nponvoie",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "npoinwefl",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
  {
    name: "aspofnwo",
    title: "Actor",
    location: "Vancouver, BC",
    age: 28,
    image: "/hero.jpg",
  },
];
