export const skillOptions = [
  { value: "acting", skill: "acting", label: "Acting" },
  { value: "comedy", skill: "comedy", label: "Comedy" },
  { value: "dance", skill: "dance", label: "Dance" },
  { value: "martial_arts", skill: "martial_arts", label: "Martial Arts" },
  { value: "model", skill: "model", label: "Model" },
  { value: "music", skill: "music", label: "Music" },
  { value: "stunt", skill: "stunt", label: "Stunt" },
  { value: "voiceover", skill: "voiceover", label: "Voiceover" },
  {
    value: "weapon_training",
    skill: "weapon_training",
    label: "Weapon training",
  },
  { value: "juggling", skill: "juggling", label: "Juggling" },
  { value: "sports", skill: "sports", label: "Sport" },
  { value: "acrobatics", skill: "acrobatics", label: "Acrobatics" },
  { value: "tongue_twister", skill: "tongue_twister", label: "Tongue twister" },
  { value: "illustration", skill: "illustration", label: "Illustration" },
  { value: "drawing", skill: "drawing", label: "Drawing" },
  { value: "photography", skill: "photography", label: "Photography" },
  { value: "video_editing", skill: "video_editing", label: "Video editing" },
  { value: "hairstyling", skill: "hairstyling", label: "Hairstyling" },
  {
    value: "kimono_dressing",
    skill: "kimono_dressing",
    label: "Kimono dressing",
  },
  {
    value: "commercial_makeup",
    skill: "commercial_makeup",
    label: "Commercial makeup",
  },
  {
    value: "special_effect_makeup",
    skill: "special_effect_makeup",
    label: "Special effect makeup",
  },
];
